### ISSUE TITLE
People backtrack

### ISSUE THREAD

**Issue by rahulon12** [gtiosclub/CanvasPlusPlayground#22]
Feature to show how many past courses you’ve had with a person in the people list

**Comment by mko02** [comment]
Sadly, if a student finishes a course, they lose access to enrollments, unless you're the professor or a TA. Another way we can do this is, if a user makes a CanvasPlus account, we fetch their past enrollments ids and save it to our database. This way, we can use the database to see common past courses. But downside is this will only work if a lot of people makes a CanvasPlus account.

**Comment by rahulon12** [comment]
Hmm are you sure? If we change our model to fetch all enrollments instead of just active enrollments, won't this work?

**Comment by mko02** [comment]
We can close this
