### ISSUE TITLE
Caching server data

### ISSUE THREAD

**Issue by rahulon12** [gtiosclub/CanvasPlusPlayground#39]

**Comment by rahulon12** [comment]
I'm hoping we can use this: https://developer.apple.com/documentation/swiftdata/maintaining-a-local-copy-of-server-data

**Comment by azooz2003-bit** [comment]
> I'm hoping we can use this: https://developer.apple.com/documentation/swiftdata/maintaining-a-local-copy-of-server-data

Yup. Was thinking about using SwiftData. Less complexity.
