### ISSUE TITLE
Preserve Navigation State

### ISSUE THREAD

**Issue by rahulon12** [gtiosclub/CanvasPlusPlayground#40]

**Comment by iWatger** [comment]
Now thinking about it, will I be able to implement this now, or should I wait until the cache system works? I'm thinking how do you display a course's people upon opening the app, if that data isn't stored in the model until the canvas api requests are made

**Comment by rahulon12** [comment]
If you look at the `NavigationModel`, we keep track of the selected course and the selected course "page". I was hoping that we could just store a copy of those in user defaults using `SceneStorage`. I'm confused why we should wait for caching if we can do it like this? Unless I'm missing out on what you mean

**Comment by iWatger** [comment]
#46
