### ISSUE TITLE
Pre load webkit sheet when the app launches to decrease the delay.

### ISSUE THREAD

**Issue by mko02** [gtiosclub/CanvasPlusPlayground#48]
Currently, when we open up a tab, it takes a while to load. You have to click multiple buttons before it finally loads.

Reference: https://github.com/gtiosclub/CanvasPlusPlayground/pull/47

**Comment by azooz2003-bit** [comment]
@rahulon12 I'm going to close this, because we're going to use SSO for auth anyways
