### ISSUE TITLE
Token search glitch

### ISSUE THREAD

**Issue by rahulon12** [gtiosclub/CanvasPlusPlayground#86]
If the enrollment has a custom role, it is displayed after a small amount of time. I believe this is because there are duplicate entries of the same user, and when we filter it shows the entry with the wrong role for a brief period.

In this case, all the TA's are "Head TA"s, but their role is "ta" not "head ta" for a brief period.

https://github.com/user-attachments/assets/89278db8-0a31-4ab0-85e7-27b827dbbfb4

**Comment by azooz2003-bit** [comment]
@rahulon12 Is this closed?

**Comment by rahulon12** [comment]
nope

**Comment by rahulon12** [comment]
Do you have classes where there are custom roles? Like not only "Ta", but "Head TA" or something?

**Comment by azooz2003-bit** [comment]
I do, one has 5 different roles

**Comment by rahulon12** [comment]
I guess that's good; we can close this and reopen if needed.
