### ISSUE TITLE
Opening an announcement has a significant delay

### ISSUE THREAD

**Issue by rahulon12** [gtiosclub/CanvasPlusPlayground#9]
https://github.com/user-attachments/assets/8e8464b3-4e04-4845-aa3d-0a6610aa5083

**Comment by azooz2003-bit** [comment]
@rahulon12 I don't see the delay here. Can you point me to it?

**Comment by rahulon12** [comment]
The time between my click and the navigation to the next page is noticeable. Also note the graph cycle warnings

**Comment by azooz2003-bit** [comment]
> The time between my click and the navigation to the next page is noticeable. Also note the graph cycle warnings. (I realize that the exact time of my click is not obvious from the video.)

Oh ok, I see it now.

**Comment by iWatger** [comment]
It's definitely an issue with the HTML formatting code. I can look into doing this asynchronously

**Comment by iWatger** [comment]
introduced a progress view while the html renders. added in AsyncAttributedText.swift

https://github.com/user-attachments/assets/db54e226-7c8b-4c7f-a1bf-444d3b391fa8

**Comment by rahulon12** [comment]
Fixed in #2
